### ISSUE TITLE
Optimierung wird nicht vom Google PageSpeed Index erkannt

### ISSUE THREAD

**Issue by snHolst** [niklasbuechner/WOTippsEmotion#3]
Moin,

mit der aktuellen SW 5.4.5 und Fluid Modus inklusive der Nutzung von Digital Publishing ist hier eher eine höhere Ladezeit dazu gekommen und bei PageSpeed Insight hat sich nix geändert.

Ist das aktuell bekannt?

VG

**Comment by niklasbuechner** [comment]
Hallo,

nein, das ist nicht bekannt. Wirft das Plugin einen Fehler? Oder wie genau äußert sich die Inkompatibilität?

**Comment by snHolst** [comment]
Hi Niklas,

ein Fehler als solches im Quellcode o.ä. erscheint nicht - jedoch erkennt page speed insights die Änderung nicht. Der Fehler "Sichtbare Inhalte priorisieren" bleibt bestehen.

VG
Christopher

**Comment by tinect** [comment]
Hey, gibt es schon Neuigkeiten hierzu?

Viele Grüße
Sebastian

**Comment by niklasbuechner** [comment]
Aktuell sieht es so aus, dass das Plugin tiefgreifende Änderungen benötigt. Um den PageSpeed Index zufrieden zu stellen, müsste man die Webseite einmal komplett rendern, damit man nicht mehr auf das Laden des JavaScript warten muss. Da man die Webseite nicht in PHP rendern kann, muss man einen extra Webservice implementieren. Diesen Webservice werde ich **nicht** implementieren, da es ein großer zeitlicher Aufwand wäre.

Jeder der einfach nur die Einkaufswelten in die eigene Seite integrieren möchte, kann das Plugin weiterhin nutzen. Es wird allerdings keine Anpassung an den neuen PageSpeed Index geben.
